config/routes.rb
LastFM::Application.routes.draw do
  resources :fmalbums

  resources :tracks

  resources :albums

  resources :artists

end

app/models/fmalbum.rb
class Fmalbum < ActiveRecord::Base
	require 'lastfm'

	lastfm = Lastfm.new('1207594aba255b1543e706b41a99abd7', '1501885a000b9fcf1ef4d03128b90bd9')
	token = lastfm.auth.get_token

	# open 'http://www.last.fm/api/auth/?api_key=xxxxxxxxxxx&token=xxxxxxxx' and grant the application

	lastfm.session = lastfm.auth.get_session(:token => token)['1207594aba255b1543e706b41a99abd7']

end

app/controllers/fmalbums_controller.rb
class FmalbumsController < ApplicationController
  # GET /fmalbums
  # GET /fmalbums.json
  def index
    @fmalbums = Fmalbum.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @fmalbums }
    end
  end

  # GET /fmalbums/1
  # GET /fmalbums/1.json
  def show
    @fmalbum = Fmalbum.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @fmalbum }
    end
  end

  # GET /fmalbums/new
  # GET /fmalbums/new.json
  def new
    @fmalbum = Fmalbum.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @fmalbum }
    end
  end

  # GET /fmalbums/1/edit
  def edit
    @fmalbum = Fmalbum.find(params[:id])
  end

  # POST /fmalbums
  # POST /fmalbums.json
  def create
    @fmalbum = Fmalbum.new(params[:fmalbum])

    respond_to do |format|
      if @fmalbum.save
        format.html { redirect_to @fmalbum, notice: 'Fmalbum was successfully created.' }
        format.json { render json: @fmalbum, status: :created, location: @fmalbum }
      else
        format.html { render action: "new" }
        format.json { render json: @fmalbum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /fmalbums/1
  # PUT /fmalbums/1.json
  def update
    @fmalbum = Fmalbum.find(params[:id])

    respond_to do |format|
      if @fmalbum.update_attributes(params[:fmalbum])
        format.html { redirect_to @fmalbum, notice: 'Fmalbum was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @fmalbum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fmalbums/1
  # DELETE /fmalbums/1.json
  def destroy
    @fmalbum = Fmalbum.find(params[:id])
    @fmalbum.destroy

    respond_to do |format|
      format.html { redirect_to fmalbums_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/fmalbums_helper.rb
module FmalbumsHelper
end

app/views/fmalbums/_form.html.erb
<%= form_for(@fmalbum) do |f| %>
  <% if @fmalbum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fmalbum.errors.count, "error") %> prohibited this fmalbum from being saved:</h2>

      <ul>
      <% @fmalbum.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :artist %><br />
    <%= f.text_field :artist %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fmalbums/edit.html.erb
<h1>Editing fmalbum</h1>

<%= render 'form' %>

<%= link_to 'Show', @fmalbum %> |
<%= link_to 'Back', fmalbums_path %>

app/views/fmalbums/index.html.erb
<h1>Listing fmalbums</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Artist</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @fmalbums.each do |fmalbum| %>
  <tr>
    <td><%= fmalbum.name %></td>
    <td><%= fmalbum.artist %></td>
    <td><%= link_to 'Show', fmalbum %></td>
    <td><%= link_to 'Edit', edit_fmalbum_path(fmalbum) %></td>
    <td><%= link_to 'Destroy', fmalbum, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Fmalbum', new_fmalbum_path %>

app/views/fmalbums/new.html.erb
<h1>New fmalbum</h1>

<%= render 'form' %>

<%= link_to 'Back', fmalbums_path %>

app/views/fmalbums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @fmalbum.name %>
</p>

<p>
  <b>Artist:</b>
  <%= @fmalbum.artist %>
</p>


<%= link_to 'Edit', edit_fmalbum_path(@fmalbum) %> |
<%= link_to 'Back', fmalbums_path %>